### ISSUE TITLE
Unable to write to /out/

### ISSUE THREAD

**Issue by dstarke1245** [nixel2007/docker-selenium-side-runner#3]
Hey nixel2007,

I get following error message:
`Error: ENOENT: no such file or directory, open '/out/CoolTest.json'
     at Object.openSync (fs.js:438:3)

     at Object.writeFileSync (fs.js:1189:35)

     at processResults (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-cli/build/runJest.js:243:29)

     at /usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-cli/build/runJest.js:455:14

     at Generator.next (<anonymous>)

     at asyncGeneratorStep (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-cli/build/runJest.js:144:24)

     at _next (/usr/local/lib/node_modules/selenium-side-runner/node_modules/jest-cli/build/runJest.js:164:9)

     at process._tickCallback (internal/process/next_tick.js:68:7)`

Have you any idea what is causing that?

Besides that: Thank you for this image!

**Comment by nixel2007** [comment]
Hello! How do you run an images? Via included docker-compose file?

**Comment by dstarke1245** [comment]
yes 
Everything works as intended except the json file.

**Comment by nixel2007** [comment]
I've rebuilded latest tag with new version of selenium runner. Could you pull it and check again?

**Comment by dstarke1245** [comment]
okay i pulled it but it changed nothing. Could it be a simple rights issue? 
Or do i have to create "test.json" first because it says 
`
Error: ENOENT: no such file or directory, open '/out/FISHADMIN.json'
`

**Comment by dstarke1245** [comment]
I think i found the Problem:
In your "docker-compose.yml" under volumes there is:
- './out:/root/out'
i changed it to 
- './out:/out' and it worked!

**Comment by nixel2007** [comment]
Looks like something changed in --output directory parameter of selenium runner. Another workaround - set absolute directory. Check new image in 20 min (with old docker-sonarqube file)

**Comment by nixel2007** [comment]
Thanks for investigation!
